# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=6.2.2.0
last_mod_version=6.2.1.2

# Common
minecraft_version=1.21.1
java_version=21

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2024.11.17

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.197
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21, 1.22)
neo_form_version=1.21.1-20240808.144430

# Integration Mods
ts_version=6.+
mantle_version=1.11.+
tic_version=3.9.+
jei_version=19.15.0.149
bop_version=5489686
terrablender_version=5864140
glitch_core_version=5483773
byg_version=5894952
tyg_version=5691181
corgilib_version=5691275
geckolib_version=4.7
probe_version=12.0.3-5
carryon_version=5541347
patchouli_version=1.21-87
patchouli_provider_version=???
curios_version=???
ie_version=5828000
regions_version=5579932

# Mod options
mod_id=survivalistessentials
mod_name=SurvivalistEssentials
mod_author=wendall911
license=MIT
display_name=Survivalist Essentials
display_url=https://github.com/wendall911/SurvivalistEssentials
mod_description=A small mod to make the first day or two of play more believable. New early game tools, no tree punching, saws, and more!
mod_credits=ashar42 billyzekat
issue_tracker=https://github.com/wendall911/SurvivalistEssentials/issues
mod_update_branch=1.21.1

# CurseForge/Modrinth Options
release_type=release
release_versions=1.21.1
